version: '3'

services:

  registry:
    container_name: panamax_registry
    build: panamax
    image: panamax_registry:latest
    command: serve /mirror
    ports:
      - 8080:8080
    volumes:
      - ./mirror:/mirror
      - ./vendor:/vendor:ro
