version: '3'

services:

  registry:
    container_name: panamax_registry
    build: .
    image: panamax_registry:latest
    command: serve /mirror
    ports:
      - 8090:8080
    volumes:
      - ./mirror:/mirror
      - ./crates:/crates:ro
