version: '3'

services:

  registry_init:
    container_name: panamax_registry_init
    build: panamax
    command: init /mirror
    volumes:
      - ./mirror:/mirror
    networks:
      - no-internet

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
