version: '3'

services:

  push:
    build: .
    image: panamax_registry:latest
    command: sync /mirror /vendor/$CRATE_DIR
    environment:
      CRATE_DIR: ${CRATE_DIR}
    volumes:
      - ./mirror:/mirror
      - ./vendor:/vendor
