version: '3'

services:

  registry_sync:
    container_name: panamax_registry_sync
    build: panamax
    image: panamax_registry:latest
    command: sync /mirror
    volumes:
      - ./mirror:/mirror
